# static-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: app
      image: busybox
      command: [ "sh", "-c" ]
      args:
        - |
          sleep 30 && \
          echo "test" > /data/file.txt && \
          cat /data/file.txt && \
          sleep 3600
      volumeMounts:
        - mountPath: /data
          name: static-volume
  volumes:
    - name: static-volume
      persistentVolumeClaim:
        claimName: static-pvc
